services:
  dashboard:
    build: .
    container_name: minix-dashboard
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Paris
      - DASHBOARD_PIN=2006
      - SECRET_KEY=c67460737c9f66597e1983cd5ce76509c9535bfc12841d6b19bb108bb36dcbad
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GPU_WORKER_TOKEN=${GPU_WORKER_TOKEN:-}
